//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        private int PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Continent {
            get {
                return this.ContinentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinentField, value) != true)) {
                    this.ContinentField = value;
                    this.RaisePropertyChanged("Continent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        private int PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetAllCountriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        Client.ServiceReference1.GetAllCountriesResponse GetAllCountries(Client.ServiceReference1.GetAllCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCountriesResponse> GetAllCountriesAsync(Client.ServiceReference1.GetAllCountriesRequest request);
        
        // CODEGEN: Generating message contract since element name code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        Client.ServiceReference1.GetCountryByCodeResponse GetCountryByCode(Client.ServiceReference1.GetCountryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetCountryByCodeResponse> GetCountryByCodeAsync(Client.ServiceReference1.GetCountryByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        Client.ServiceReference1.GetCityByNameResponse GetCityByName(Client.ServiceReference1.GetCityByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetCityByNameResponse> GetCityByNameAsync(Client.ServiceReference1.GetCityByNameRequest request);
        
        // CODEGEN: Generating message contract since element name countryCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCitiesByCountryCode", ReplyAction="*")]
        Client.ServiceReference1.GetAllCitiesByCountryCodeResponse GetAllCitiesByCountryCode(Client.ServiceReference1.GetAllCitiesByCountryCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCitiesByCountryCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCitiesByCountryCodeResponse> GetAllCitiesByCountryCodeAsync(Client.ServiceReference1.GetAllCitiesByCountryCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountries", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetAllCountriesRequestBody Body;
        
        public GetAllCountriesRequest() {
        }
        
        public GetAllCountriesRequest(Client.ServiceReference1.GetAllCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCountriesRequestBody {
        
        public GetAllCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetAllCountriesResponseBody Body;
        
        public GetAllCountriesResponse() {
        }
        
        public GetAllCountriesResponse(Client.ServiceReference1.GetAllCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Country[] GetAllCountriesResult;
        
        public GetAllCountriesResponseBody() {
        }
        
        public GetAllCountriesResponseBody(Client.ServiceReference1.Country[] GetAllCountriesResult) {
            this.GetAllCountriesResult = GetAllCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCode", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetCountryByCodeRequestBody Body;
        
        public GetCountryByCodeRequest() {
        }
        
        public GetCountryByCodeRequest(Client.ServiceReference1.GetCountryByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        public GetCountryByCodeRequestBody() {
        }
        
        public GetCountryByCodeRequestBody(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetCountryByCodeResponseBody Body;
        
        public GetCountryByCodeResponse() {
        }
        
        public GetCountryByCodeResponse(Client.ServiceReference1.GetCountryByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.Country GetCountryByCodeResult;
        
        public GetCountryByCodeResponseBody() {
        }
        
        public GetCountryByCodeResponseBody(Client.ServiceReference1.Country GetCountryByCodeResult) {
            this.GetCountryByCodeResult = GetCountryByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByName", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetCityByNameRequestBody Body;
        
        public GetCityByNameRequest() {
        }
        
        public GetCityByNameRequest(Client.ServiceReference1.GetCityByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetCityByNameRequestBody() {
        }
        
        public GetCityByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetCityByNameResponseBody Body;
        
        public GetCityByNameResponse() {
        }
        
        public GetCityByNameResponse(Client.ServiceReference1.GetCityByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.City GetCityByNameResult;
        
        public GetCityByNameResponseBody() {
        }
        
        public GetCityByNameResponseBody(Client.ServiceReference1.City GetCityByNameResult) {
            this.GetCityByNameResult = GetCityByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesByCountryCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCitiesByCountryCode", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetAllCitiesByCountryCodeRequestBody Body;
        
        public GetAllCitiesByCountryCodeRequest() {
        }
        
        public GetAllCitiesByCountryCodeRequest(Client.ServiceReference1.GetAllCitiesByCountryCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCitiesByCountryCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetAllCitiesByCountryCodeRequestBody() {
        }
        
        public GetAllCitiesByCountryCodeRequestBody(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesByCountryCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCitiesByCountryCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetAllCitiesByCountryCodeResponseBody Body;
        
        public GetAllCitiesByCountryCodeResponse() {
        }
        
        public GetAllCitiesByCountryCodeResponse(Client.ServiceReference1.GetAllCitiesByCountryCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCitiesByCountryCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.City[] GetAllCitiesByCountryCodeResult;
        
        public GetAllCitiesByCountryCodeResponseBody() {
        }
        
        public GetAllCitiesByCountryCodeResponseBody(Client.ServiceReference1.City[] GetAllCitiesByCountryCodeResult) {
            this.GetAllCitiesByCountryCodeResult = GetAllCitiesByCountryCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.WebService1Soap>, Client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetAllCountriesResponse Client.ServiceReference1.WebService1Soap.GetAllCountries(Client.ServiceReference1.GetAllCountriesRequest request) {
            return base.Channel.GetAllCountries(request);
        }
        
        public Client.ServiceReference1.Country[] GetAllCountries() {
            Client.ServiceReference1.GetAllCountriesRequest inValue = new Client.ServiceReference1.GetAllCountriesRequest();
            inValue.Body = new Client.ServiceReference1.GetAllCountriesRequestBody();
            Client.ServiceReference1.GetAllCountriesResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetAllCountries(inValue);
            return retVal.Body.GetAllCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCountriesResponse> Client.ServiceReference1.WebService1Soap.GetAllCountriesAsync(Client.ServiceReference1.GetAllCountriesRequest request) {
            return base.Channel.GetAllCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCountriesResponse> GetAllCountriesAsync() {
            Client.ServiceReference1.GetAllCountriesRequest inValue = new Client.ServiceReference1.GetAllCountriesRequest();
            inValue.Body = new Client.ServiceReference1.GetAllCountriesRequestBody();
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetAllCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetCountryByCodeResponse Client.ServiceReference1.WebService1Soap.GetCountryByCode(Client.ServiceReference1.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCode(request);
        }
        
        public Client.ServiceReference1.Country GetCountryByCode(string code) {
            Client.ServiceReference1.GetCountryByCodeRequest inValue = new Client.ServiceReference1.GetCountryByCodeRequest();
            inValue.Body = new Client.ServiceReference1.GetCountryByCodeRequestBody();
            inValue.Body.code = code;
            Client.ServiceReference1.GetCountryByCodeResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetCountryByCode(inValue);
            return retVal.Body.GetCountryByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetCountryByCodeResponse> Client.ServiceReference1.WebService1Soap.GetCountryByCodeAsync(Client.ServiceReference1.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetCountryByCodeResponse> GetCountryByCodeAsync(string code) {
            Client.ServiceReference1.GetCountryByCodeRequest inValue = new Client.ServiceReference1.GetCountryByCodeRequest();
            inValue.Body = new Client.ServiceReference1.GetCountryByCodeRequestBody();
            inValue.Body.code = code;
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetCountryByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetCityByNameResponse Client.ServiceReference1.WebService1Soap.GetCityByName(Client.ServiceReference1.GetCityByNameRequest request) {
            return base.Channel.GetCityByName(request);
        }
        
        public Client.ServiceReference1.City GetCityByName(string name) {
            Client.ServiceReference1.GetCityByNameRequest inValue = new Client.ServiceReference1.GetCityByNameRequest();
            inValue.Body = new Client.ServiceReference1.GetCityByNameRequestBody();
            inValue.Body.name = name;
            Client.ServiceReference1.GetCityByNameResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetCityByName(inValue);
            return retVal.Body.GetCityByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetCityByNameResponse> Client.ServiceReference1.WebService1Soap.GetCityByNameAsync(Client.ServiceReference1.GetCityByNameRequest request) {
            return base.Channel.GetCityByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetCityByNameResponse> GetCityByNameAsync(string name) {
            Client.ServiceReference1.GetCityByNameRequest inValue = new Client.ServiceReference1.GetCityByNameRequest();
            inValue.Body = new Client.ServiceReference1.GetCityByNameRequestBody();
            inValue.Body.name = name;
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetCityByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetAllCitiesByCountryCodeResponse Client.ServiceReference1.WebService1Soap.GetAllCitiesByCountryCode(Client.ServiceReference1.GetAllCitiesByCountryCodeRequest request) {
            return base.Channel.GetAllCitiesByCountryCode(request);
        }
        
        public Client.ServiceReference1.City[] GetAllCitiesByCountryCode(string countryCode) {
            Client.ServiceReference1.GetAllCitiesByCountryCodeRequest inValue = new Client.ServiceReference1.GetAllCitiesByCountryCodeRequest();
            inValue.Body = new Client.ServiceReference1.GetAllCitiesByCountryCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            Client.ServiceReference1.GetAllCitiesByCountryCodeResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetAllCitiesByCountryCode(inValue);
            return retVal.Body.GetAllCitiesByCountryCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCitiesByCountryCodeResponse> Client.ServiceReference1.WebService1Soap.GetAllCitiesByCountryCodeAsync(Client.ServiceReference1.GetAllCitiesByCountryCodeRequest request) {
            return base.Channel.GetAllCitiesByCountryCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetAllCitiesByCountryCodeResponse> GetAllCitiesByCountryCodeAsync(string countryCode) {
            Client.ServiceReference1.GetAllCitiesByCountryCodeRequest inValue = new Client.ServiceReference1.GetAllCitiesByCountryCodeRequest();
            inValue.Body = new Client.ServiceReference1.GetAllCitiesByCountryCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetAllCitiesByCountryCodeAsync(inValue);
        }
    }
}
